In [124]:
import numpy as np
import scipy.constants
import matplotlib.pyplot as plt



class Lattice:
    def __init__(self,n = 4,m = 10, T = 298, mean = 0.0):
        np.random.seed(0)
        #xdim
        self.m = m
        #ydim
        self.n = n
        self.beta = 1 / (scipy.constants.k * T)
        self.mean = mean
        self.lattice = self.generate_lattice()
        

    
    def generate_lattice(self):
        #generating m x n lattice of -1,1 spins
        #with mean value of self.mean
        choices = np.array([-1,1])
        p = 0.5 * (self.mean+1)
        p_choices = [1-p,p]
        lattice = np.random.choice(choices, p = p_choices, size = (self.n, self.m))
        return lattice
    

    def flip_energy(self, k = 4,site = [0,0], axis = 1):
        #calculate the energy change of k-spin flip with specififed site and orientation
        #axis: [1,-1,2,-2]
        #site: [0:m-1,0:n-1]

        sitex = site[0]
        sitey = site[1]
        print(site)
        #extract k_string padded with 1 width of neighbours on x and y
        if axis == 1:
            x_indices = (sitex-1 + np.arange(k+2)) % self.m
            y_indices = [(sitey - 1) % self.n, sitey % self.n, (sitey + 1) % self.n]
            print('x,y')
            print(x_indices)
            print(y_indices)
        k_string = self.lattice[y_indices,x_indices[:, None]]
        print('')
        print(k_string)
        print(k_string.shape)



        E = 0
        for i in range(1,k+1):
            E += k_string[i][1] * (k_string[i][0] + k_string[i][2])
            print(E)
        E += k_string[0][1] * k_string[1][1]
        E += k_string[-1][1] * k_string[-2][1]
        
        #performing flip inverts these interaction energies
        E *= -1
        return E

        #if np.rand() <= np.exp(self.beta * E):
            #self.do_flip(k,site = site, axis = 1)

    def do_flip(self,k=4,site=[0,1],axis = 1):
        sitex = site[0]
        sitey = site[1]
        x_indices = (sitex + np.arange(k)) % self.m
        y_indices = [sitey]
        print(self.lattice)
        self.lattice[y_indices,x_indices[:, None]] *= -1
        print('flipping site ' + str(sitex) + str(sitey) + ', k=' + str(k))
        print(self.lattice)






    




L = Lattice(mean = 0.5)
print(L.lattice)
print('')
#L.flip_energy(site = [0,0],k = 7)

#L.flip_energy(site = [2,1],k = 3, axis = 1)

L.do_flip(k=5)







[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1 -1 -1 -1  1  1  1]
 [ 1  1  1  1 -1  1 -1  1  1  1]
 [ 1  1  1  1 -1  1  1  1  1  1]]

[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1 -1 -1 -1  1  1  1]
 [ 1  1  1  1 -1  1 -1  1  1  1]
 [ 1  1  1  1 -1  1  1  1  1  1]]
flipping site 01, k=5
[[ 1  1  1  1  1  1  1  1  1  1]
 [-1 -1 -1 -1  1 -1 -1  1  1  1]
 [ 1  1  1  1 -1  1 -1  1  1  1]
 [ 1  1  1  1 -1  1  1  1  1  1]]
